"""Initial migration.

Revision ID: 9f1e34d95d02
Revises: 
Create Date: 2023-03-24 17:45:08.069116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1e34d95d02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('opening_time', sa.String(length=5), nullable=False),
    sa.Column('closing_time', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('product',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('sugar_percentage', sa.Float(), nullable=False),
    sa.Column('saturated_fats_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('name', 'brand'),
    sa.UniqueConstraint('name', 'brand', name='unique_product_brand')
    )
    op.create_table('product_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_name', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['market_name'], ['market.name'], ),
    sa.ForeignKeyConstraint(['product_name'], ['product.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_price')
    op.drop_table('product')
    op.drop_table('market')
    # ### end Alembic commands ###
